corner-radius = 16;
round-borders = 1;
backend = "glx";

shadow-exclude = [
	"class_g = 'slop'",
	"class_g = 'scrot'"
];

no-fading-openclose = true;
detect-rounded-corners = true;

opacity-rule = [
    "100:class_g = 'slop'",
    "100:class_g = 'scrot'"
];

wintypes:
{
  tooltip = { fade = false; shadow = false; opacity = 1.0; };
  utility = { shadow = false; };
  dock = { shadow = false; };
  dnd = { shadow = false; };
}
